spring.application.name=CursiFy

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bd_cursify;integratedSecurity=false;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@ITB123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true