spring.application.name=CursiFy

server.port=8080

# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bd_cursify;integratedSecurity=false;encrypt=false;trustServerCertificate=true
# spring.datasource.username=sa
# spring.datasource.password=@ITB123456

spring.datasource.url=jdbc:sqlserver://bd_cursify.mssql.somee.com;databaseName=bd_cursify;integratedSecurity=false;encrypt=true;trustServerCertificate=true
spring.datasource.username=CursiFy
spring.datasource.password=CursiFy@0123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true

# Informacoes:

# integratedSecurity: (true) Indica que a conexao sera feita com as credenciais do Windows (false) Credencial do Sql Server
# encrypt: (true) Requer criptografia do cliente (false) nao requer criptografia do cliente
# trustServerCertificate: (true) Instrui o aplicativo cliente a ignorar a validacao do certificado SSL/TSL do servidor

# spring.jpa.hibernate.ddl-auto
# Pode receber os seguintes valores:
# none    -> Banco de dados e tabelas devem ser criados com antecedencia
# update  -> Banco de dados e tabelas devem ser criados com antecedencia, o codigo atualiza as tabelas toda vez que ha alteracoes no codigo
# create-drop -> Banco de dados deve ser criado com antecedencia, o codigo cria as tabelas entretanto, quando o servidor e desligado, as tabelas
#                serao excluidas
# create  -> Banco de dados deve ser criado com antecedencia, quando o servidor carrega as informacoes as tabelas sao recriadas
