spring.application.name=CursiFy

server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.flyway.enabled=false
cursify.jwt.secret=ChangeThisSecretForCursiFy

# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bd_cursify;integratedSecurity=false;encrypt=false;trustServerCertificate=true
# spring.datasource.username=sa
# spring.datasource.password=@ITB123456

spring.datasource.url=jdbc:sqlserver://bd_cursify.mssql.somee.com;databaseName=bd_cursify;integratedSecurity=false;encrypt=true;trustServerCertificate=true
spring.datasource.username=CursiFy
spring.datasource.password=CursiFy@0123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.open-in-view=false

# Informacoes
# integratedSecurity: true usa credenciais do Windows; false usa credenciais do SQL Server
# encrypt: true exige criptografia do cliente; false nao exige
# trustServerCertificate: true ignora a validacao do certificado SSL/TLS do servidor

# spring.jpa.hibernate.ddl-auto
# none        -> Banco de dados e tabelas devem existir antes da inicializacao
# update      -> Atualiza as tabelas de acordo com as entidades
# create-drop -> Cria no inicio e remove ao desligar
# create      -> Recria as tabelas a cada inicializacao
